package com.JavaComp.interf;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import com.JavaComp.program.*;

public class ConsultarUsuarios extends javax.swing.JFrame {
    

    
    public ConsultarUsuarios() {
        initComponents(); 
        agregarFilaATabla();
    
    }
    private void agregarFilaATabla(){
            DefaultTableModel modelo =(DefaultTableModel) usuariosTabla.getModel();
            ArrayList<Cliente> clientes = DataManager.getClientes();
            Object datoFila []=new Object[8];
            for(int i = 0; i<clientes.size(); i++){
            
                datoFila[4] = clientes.get(i).getNombre();
                datoFila[5] = clientes.get(i).getCorreo();
                datoFila[6] = clientes.get(i).getTelefono();
                datoFila[7] = clientes.get(i).getNumPedidos();
                if (clientes.get(i) instanceof Particular){
                Particular particular = (Particular) clientes.get(i);
                datoFila[0] = "Si";
                datoFila[1] = "-";
                datoFila[2] = particular.getDni();
                datoFila[3] ="-";
                }
                else{
                Empresa empresa = (Empresa) clientes.get(i);
                datoFila[0] ="-";
                datoFila[1]="Si";
                datoFila[2]= empresa.getCif();
                datoFila[3]= empresa.getWeb();
                }
                modelo.addRow(datoFila);
            }
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverBoton = new javax.swing.JButton();
        imprimirBoton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usuariosTabla = new javax.swing.JTable();
        consultarVentasBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaComp");
        setIconImage(new javax.swing.ImageIcon("src/main/resources/images/LogoJavaComp.png").getImage());

        volverBoton.setText("Volver");
        volverBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBotonActionPerformed(evt);
            }
        });

        imprimirBoton.setText("Imprimir");
        imprimirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirBotonActionPerformed(evt);
            }
        });

        usuariosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Particular", "Empresa", "DNI/CIF", "Web", "Nombre", "Correo", "Teléfono", "Número pedidos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(usuariosTabla);

        consultarVentasBoton.setText("Consultar pedidos");
        consultarVentasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarVentasBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(volverBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                        .addComponent(consultarVentasBoton)
                        .addGap(236, 236, 236)
                        .addComponent(imprimirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(imprimirBoton)
                        .addComponent(consultarVentasBoton))
                    .addComponent(volverBoton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBotonActionPerformed
        this.setVisible(false);
        InterfAdmin interfAdmin = new InterfAdmin();
        interfAdmin.setLocationRelativeTo(null);
        interfAdmin.setVisible(true);
    }//GEN-LAST:event_volverBotonActionPerformed

    private void consultarVentasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarVentasBotonActionPerformed
        this.setVisible(false);
        ConsultarVentas ventas = new ConsultarVentas();
        ventas.setLocationRelativeTo(null);
        ventas.setVisible(true);
    }//GEN-LAST:event_consultarVentasBotonActionPerformed

    private void imprimirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirBotonActionPerformed
        try{
            usuariosTabla.print();
        }
        catch(Exception e){
                e.printStackTrace();
        };
    }//GEN-LAST:event_imprimirBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarVentasBoton;
    private javax.swing.JButton imprimirBoton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable usuariosTabla;
    private javax.swing.JButton volverBoton;
    // End of variables declaration//GEN-END:variables
}
