/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.JavaComp.interf;

import com.JavaComp.program.DataManager;
import java.time.LocalDate;
import java.time.ZoneId;

/**
 *
 * @author Kar�n
 */
public class ConsultarVentas extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarVentas
     */
    public ConsultarVentas() {
        initComponents();
        DataManager.displayVenta(DataManager.getPedidos(), pedidosPanel);
        pedidosScroll.getVerticalScrollBar().setUnitIncrement(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverBoton = new javax.swing.JButton();
        pedidosScroll = new javax.swing.JScrollPane();
        pedidosPanel = new javax.swing.JPanel();
        filtroFecha = new org.jdatepicker.JDatePicker();
        jLabel1 = new javax.swing.JLabel();
        mostratTodoBoton = new javax.swing.JButton();
        selectorBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaComp");
        setIconImage(new javax.swing.ImageIcon("src/main/resources/images/LogoJavaComp.png").getImage());

        volverBoton.setText("Volver");
        volverBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBotonActionPerformed(evt);
            }
        });

        pedidosPanel.setLayout(new javax.swing.BoxLayout(pedidosPanel, javax.swing.BoxLayout.Y_AXIS));
        pedidosScroll.setViewportView(pedidosPanel);

        filtroFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroFechaActionPerformed(evt);
            }
        });

        jLabel1.setText("Ver ventas");

        mostratTodoBoton.setText("Mostrar Todo");
        mostratTodoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostratTodoBotonActionPerformed(evt);
            }
        });

        selectorBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "antes de", "después de" }));
        selectorBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pedidosScroll)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(volverBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectorBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filtroFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostratTodoBoton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pedidosScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(volverBoton)
                        .addComponent(jLabel1)
                        .addComponent(selectorBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(filtroFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostratTodoBoton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBotonActionPerformed
       this.setVisible(false);
       InterfAdmin interfazAdmin = new InterfAdmin();
       interfazAdmin.setLocationRelativeTo(null);
       interfazAdmin.setVisible(true);
    }//GEN-LAST:event_volverBotonActionPerformed

    private void filtroFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroFechaActionPerformed
        if (filtroFecha.getModel().getValue() != null){
            //Convierte el output de filtroFecha en un GregorianCalendar
            java.util.GregorianCalendar calendar = (java.util.GregorianCalendar) filtroFecha.getModel().getValue();
            //Convierte el GregorianCalendar en tipo Date
            java.util.Date date = java.util.Date.from(calendar.toZonedDateTime().toInstant());
            //Convierte el Date en LocalDate
            LocalDate localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            //Filtra por fecha los pedidos con el LocalDate y los muestra
            if (selectorBox.getSelectedItem().equals("después de"))
                DataManager.displayVenta(DataManager.filtrarFecha(true, localDate, DataManager.getPedidos()), pedidosPanel);
            else if (selectorBox.getSelectedItem().equals("antes de"))
                DataManager.displayVenta(DataManager.filtrarFecha(false, localDate, DataManager.getPedidos()), pedidosPanel);
        }
        
    }//GEN-LAST:event_filtroFechaActionPerformed

    private void mostratTodoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostratTodoBotonActionPerformed
        // TODO add your handling code here:
        DataManager.displayVenta(DataManager.getPedidos(), pedidosPanel);
        filtroFecha.getFormattedTextField().setText("");
    }//GEN-LAST:event_mostratTodoBotonActionPerformed

    private void selectorBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorBoxActionPerformed
        if (filtroFecha.getModel().getValue() != null){
            //Convierte el output de filtroFecha en un GregorianCalendar
            java.util.GregorianCalendar calendar = (java.util.GregorianCalendar) filtroFecha.getModel().getValue();
            //Convierte el GregorianCalendar en tipo Date
            java.util.Date date = java.util.Date.from(calendar.toZonedDateTime().toInstant());
            //Convierte el Date en LocalDate
            LocalDate localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            //Filtra por fecha los pedidos con el LocalDate y los muestra
            if (selectorBox.getSelectedItem().equals("después de"))
                DataManager.displayVenta(DataManager.filtrarFecha(true, localDate, DataManager.getPedidos()), pedidosPanel);
            else if (selectorBox.getSelectedItem().equals("antes de"))
                DataManager.displayVenta(DataManager.filtrarFecha(false, localDate, DataManager.getPedidos()), pedidosPanel);
        }
    }//GEN-LAST:event_selectorBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdatepicker.JDatePicker filtroFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mostratTodoBoton;
    private javax.swing.JPanel pedidosPanel;
    private javax.swing.JScrollPane pedidosScroll;
    private javax.swing.JComboBox<String> selectorBox;
    private javax.swing.JButton volverBoton;
    // End of variables declaration//GEN-END:variables
}
