/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.JavaComp.interf;

import com.JavaComp.program.Pedido;
import com.JavaComp.program.Producto;

/**
 *
 * @author Slend
 */
public class DisplayVenta extends javax.swing.JPanel {

    /**
     * Creates new form DisplayVenta
     * @param venta la venta que se va a mostrar
     */
    public DisplayVenta(Pedido venta) {
        initComponents();
        String texto = "";
        for (Producto p : venta.getCarrito()){
            texto += "** " + p.getTitulo() + " **\n";
            texto += "Cantidad: " + p.getStock() + "\n";
            texto += "Precio: " + Double.toString(p.getPvp()*p.getStock()) + "€ (" + Double.toString(p.getPvp()) + "€/ud)\n";
            texto += "Categoria: " + p.getCategoria() + "\n\n";
        }
        productosArea.setText(texto);
        fechaLabel.setText("** " + venta.getFechaPedido().toString().toUpperCase() + " **");
        nombreLabel.setText("Nombre: " + venta.getCliente().getNombre());
        correoLabel.setText("Correo: " + venta.getCliente().getCorreo());
        tarjetaLabel.setText("Tarjeta: **** **** **** " + venta.getCliente().getTarjeta().getCodigo().substring(15));
        telefonoLabel.setText("Teléfono: " + venta.getCliente().getTelefono());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fechaLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        correoLabel = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        tarjetaLabel = new javax.swing.JLabel();
        productosScroll = new javax.swing.JScrollPane();
        productosArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        fechaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaLabel.setText("FechaVenta");

        nombreLabel.setText("nombreCliente");

        correoLabel.setText("correoCliente");

        telefonoLabel.setText("TelefonoCliente");

        tarjetaLabel.setText("tarjetaCliente");

        productosArea.setEditable(false);
        productosArea.setColumns(20);
        productosArea.setLineWrap(true);
        productosArea.setRows(5);
        productosArea.setWrapStyleWord(true);
        productosScroll.setViewportView(productosArea);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("** DATOS DEL CLIENTE ** ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreLabel)
                            .addComponent(tarjetaLabel)
                            .addComponent(correoLabel)
                            .addComponent(telefonoLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productosScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fechaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(correoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(telefonoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tarjetaLabel))
                    .addComponent(productosScroll))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel correoLabel;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextArea productosArea;
    private javax.swing.JScrollPane productosScroll;
    private javax.swing.JLabel tarjetaLabel;
    private javax.swing.JLabel telefonoLabel;
    // End of variables declaration//GEN-END:variables
}
