/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.JavaComp.interf;

import com.JavaComp.program.DataManager;
import com.JavaComp.program.Producto;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 * Esta es la case que enseña los productos que existen en el carro dentro de InterfCarro
 * 
 * @author Pablo
 * @author Karin
 */
public class DisplayProdCarro extends javax.swing.JPanel {

    /**
     * Inicializa los diferentes campos para que coincidan con los datos del producto prod
     * @param prod
     */
    public DisplayProdCarro(Producto prod) {
        initComponents();
        this.prod = prod;
        cantidadLabel.setText("Cantidad: " + prod.getStock() + " uds");
        precioLabel.setText("Precio: " + String.format("%.2f",(prod.getPvp()*prod.getStock())) + "€ (" + prod.getPvp() + "€/ud)");
        ImageIcon imageIcon = new ImageIcon(prod.getImagen()); // load the image to a imageIcon
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(76, 72,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg);
        imagenLabel.setIcon(imageIcon);
        imagenLabel.setText("");
        tituloLabel.setText(prod.getTitulo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        cantidadLabel = new javax.swing.JLabel();
        precioLabel = new javax.swing.JLabel();
        retirarBoton = new javax.swing.JButton();

        imagenLabel.setText("Imagen");

        tituloLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tituloLabel.setText("Titulo");

        cantidadLabel.setText("Cantidad:");

        precioLabel.setText("Precio:");

        retirarBoton.setBackground(new java.awt.Color(255, 191, 29));
        retirarBoton.setForeground(new java.awt.Color(51, 51, 51));
        retirarBoton.setText("Retirar");
        retirarBoton.setFocusPainted(false);
        retirarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantidadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(retirarBoton))
                    .addComponent(precioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloLabel)
                            .addComponent(retirarBoton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(precioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadLabel))
                    .addComponent(imagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void retirarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirarBotonActionPerformed
        ArrayList<Producto> array = DataManager.getCarritoActual();
        array.remove(prod);
        DataManager.setCarritoActual(array);
        parent.reload();
    }//GEN-LAST:event_retirarBotonActionPerformed

    /**
     * parent es el jframe que contiene este jpanel
     * @param parent
     */
    public void setParent(InterfCarro parent) {
        this.parent = parent;
    }

    /**
     * prod es el producto que este display está mostrando
     * @param prod
     */
    public void setProd(Producto prod) {
        this.prod = prod;
    }
    
    private InterfCarro parent;
    private Producto prod;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantidadLabel;
    private javax.swing.JLabel imagenLabel;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JButton retirarBoton;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
