/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.JavaComp.interf;

import com.JavaComp.program.DataManager;
import com.JavaComp.program.Pedido;
import java.util.ArrayList;

/**
 *
 * @author Slend
 */
public class InterfCarro extends javax.swing.JFrame {

    /**
     * Creates new form InterfCarro
     * @param prevFrame
     */
    public InterfCarro(javax.swing.JFrame prevFrame) {
        initComponents();
        this.prevFrame = prevFrame;
        reload();
    }
    
    public void reload(){
        DataManager.displayCarrito(carroPanel, this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carritoScroll = new javax.swing.JScrollPane();
        carroPanel = new javax.swing.JPanel();
        finalizarBoton = new javax.swing.JButton();
        volverBoton = new javax.swing.JButton();
        explicacionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaComp");
        setIconImage(new javax.swing.ImageIcon("src/main/resources/images/LogoJavaComp.png").getImage());

        carritoScroll.setBorder(null);

        carroPanel.setLayout(new javax.swing.BoxLayout(carroPanel, javax.swing.BoxLayout.PAGE_AXIS));
        carritoScroll.setViewportView(carroPanel);

        finalizarBoton.setBackground(new java.awt.Color(242, 180, 27));
        finalizarBoton.setForeground(new java.awt.Color(51, 51, 51));
        finalizarBoton.setText("Finalizar compra");
        finalizarBoton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        finalizarBoton.setFocusPainted(false);
        finalizarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarBotonActionPerformed(evt);
            }
        });

        volverBoton.setBackground(new java.awt.Color(242, 180, 27));
        volverBoton.setForeground(new java.awt.Color(51, 51, 51));
        volverBoton.setText("Volver");
        volverBoton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        volverBoton.setFocusPainted(false);
        volverBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBotonActionPerformed(evt);
            }
        });

        explicacionLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        explicacionLabel.setText("Vas a comprar los siguientes artículos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(volverBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finalizarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(explicacionLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(carritoScroll)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(explicacionLabel)
                .addGap(12, 12, 12)
                .addComponent(carritoScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finalizarBoton)
                    .addComponent(volverBoton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBotonActionPerformed
        // TODO add your handling code here:
        prevFrame.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_volverBotonActionPerformed

    private void finalizarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarBotonActionPerformed
        // TODO add your handling code here:
        Pedido compra = new Pedido(DataManager.getClienteActual(), DataManager.getCarritoActual());
        compra.toText();
        if(!compra.comprar(this)){
            DataManager.setCarritoActual(new ArrayList());
            this.setVisible(false);
            InterfCliente interf = new InterfCliente();
            interf.setLocationRelativeTo(null);
            interf.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_finalizarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    private final javax.swing.JFrame prevFrame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane carritoScroll;
    private javax.swing.JPanel carroPanel;
    private javax.swing.JLabel explicacionLabel;
    private javax.swing.JButton finalizarBoton;
    private javax.swing.JButton volverBoton;
    // End of variables declaration//GEN-END:variables
}
