/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.JavaComp.interf;

import com.JavaComp.program.Opinion;
import com.JavaComp.program.Producto;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Slend
 */
public class InterfProducto extends javax.swing.JFrame {

    /**
     * Creates new form InterfProducto
     */
    public InterfProducto() {
        initComponents();
    }
    
    public void setInterfaz(){
        tituloLabel.setText(prod.getTitulo());
        stockLabel.setText("Unidades restantes: " + prod.getStock());
        precioLabel.setText(prod.getPvp() + "€");
        String opiniones = "";
        int rating = 0;
        if (prod.getOpiniones() != null){
            for (Opinion op : prod.getOpiniones()){
            opiniones = opiniones + "** " + op.getFecha() + "\t" + op.getCalif() + "☆" + " **" + "\n";
            opiniones = opiniones + op.getComentario() + "\n\n";
            rating += op.getCalif();
            }
            rating = rating / prod.getOpiniones().size();
        }
        ratingsLabel.setText(rating + "☆");
        opinionesArea.setText(opiniones);
        descripcionArea.setText(prod.getCaracteristicas());
        fechaLabel.setText(prod.getFechaEntrada().toString());
        
        ImageIcon imageIcon = new ImageIcon(prod.getImagen()); // load the image to a imageIcon
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(176, 120,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg);
        imagenLabel.setText("");
        imagenLabel.setIcon(imageIcon);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLabel = new javax.swing.JLabel();
        precioLabel = new javax.swing.JLabel();
        descripcionScroll = new javax.swing.JScrollPane();
        descripcionArea = new javax.swing.JTextArea();
        numCarrito = new javax.swing.JSpinner();
        confirmarBoton = new javax.swing.JButton();
        cancelarBoton = new javax.swing.JButton();
        imagenLabel = new javax.swing.JLabel();
        stockLabel = new javax.swing.JLabel();
        ratingsLabel = new javax.swing.JLabel();
        opinionesScroll = new javax.swing.JScrollPane();
        opinionesArea = new javax.swing.JTextArea();
        opinarBoton = new javax.swing.JButton();
        fechaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloLabel.setText("Titulo");

        precioLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        precioLabel.setText("Precio");

        descripcionScroll.setBorder(null);

        descripcionArea.setEditable(false);
        descripcionArea.setColumns(20);
        descripcionArea.setLineWrap(true);
        descripcionArea.setRows(5);
        descripcionArea.setText("Descripcion");
        descripcionArea.setToolTipText("");
        descripcionArea.setWrapStyleWord(true);
        descripcionScroll.setViewportView(descripcionArea);

        confirmarBoton.setText("Añadir al carrito");

        cancelarBoton.setText("Cancelar");

        imagenLabel.setText("Imagen");

        stockLabel.setText("Unidades restantes:");

        ratingsLabel.setText("Ratings");

        opinionesScroll.setBorder(null);

        opinionesArea.setEditable(false);
        opinionesArea.setColumns(20);
        opinionesArea.setLineWrap(true);
        opinionesArea.setRows(5);
        opinionesArea.setText("Opiniones");
        opinionesArea.setWrapStyleWord(true);
        opinionesScroll.setViewportView(opinionesArea);

        opinarBoton.setText("Opinar");
        opinarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opinarBotonActionPerformed(evt);
            }
        });

        fechaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaLabel.setText("Fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelarBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opinarBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmarBoton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(imagenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descripcionScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(opinionesScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ratingsLabel)
                                .addGap(18, 18, 18)
                                .addComponent(fechaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloLabel)
                    .addComponent(stockLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(precioLabel)
                    .addComponent(ratingsLabel)
                    .addComponent(fechaLabel))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(descripcionScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(opinionesScroll)
                    .addComponent(imagenLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmarBoton)
                    .addComponent(cancelarBoton)
                    .addComponent(opinarBoton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opinarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opinarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opinarBotonActionPerformed

    public void setProd(Producto prod) {
        this.prod = prod;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfProducto().setVisible(true);
            }
        });
    }
    private Producto prod;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarBoton;
    private javax.swing.JButton confirmarBoton;
    private javax.swing.JTextArea descripcionArea;
    private javax.swing.JScrollPane descripcionScroll;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel imagenLabel;
    private javax.swing.JSpinner numCarrito;
    private javax.swing.JButton opinarBoton;
    private javax.swing.JTextArea opinionesArea;
    private javax.swing.JScrollPane opinionesScroll;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JLabel ratingsLabel;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
