/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.JavaComp.interf;

import com.JavaComp.program.DataManager;
import com.JavaComp.program.Opinion;
import com.JavaComp.program.Producto;
import java.time.LocalDate;
import java.util.ArrayList;

/**
 *
 * @author Slend
 */
public class InterfOpinar extends javax.swing.JFrame {

    /**
     * Creates new form InterfOpinar
     * @param frame
     * @param prod
     */
    public InterfOpinar(InterfProducto frame, Producto prod) {
        initComponents();
        this.prevFrame = frame;
        this.prod = prod;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opinionScroll = new javax.swing.JScrollPane();
        opinionArea = new javax.swing.JTextArea();
        confirmarBoton = new javax.swing.JButton();
        ratingSpinner = new javax.swing.JSpinner();
        explicacionLabel = new javax.swing.JLabel();
        canclelarButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaComp");
        setIconImage(new javax.swing.ImageIcon("src/main/resources/images/LogoJavaComp.png").getImage());

        opinionScroll.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));

        opinionArea.setColumns(20);
        opinionArea.setLineWrap(true);
        opinionArea.setRows(5);
        opinionArea.setWrapStyleWord(true);
        opinionScroll.setViewportView(opinionArea);

        confirmarBoton.setBackground(new java.awt.Color(255, 191, 29));
        confirmarBoton.setForeground(new java.awt.Color(51, 51, 51));
        confirmarBoton.setText("Publicar opinión");
        confirmarBoton.setFocusPainted(false);
        confirmarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarBotonActionPerformed(evt);
            }
        });

        ratingSpinner.setModel(new javax.swing.SpinnerNumberModel(5, 1, 5, 1));
        ratingSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ratingSpinnerStateChanged(evt);
            }
        });

        explicacionLabel.setText("Por favor denos su opinión sobre el poducto:");

        canclelarButon.setBackground(new java.awt.Color(255, 191, 29));
        canclelarButon.setForeground(new java.awt.Color(51, 51, 51));
        canclelarButon.setText("Cancelar");
        canclelarButon.setFocusPainted(false);
        canclelarButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canclelarButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opinionScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(canclelarButon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmarBoton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(explicacionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ratingSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ratingSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(explicacionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opinionScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarBoton)
                    .addComponent(canclelarButon))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ratingSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ratingSpinnerStateChanged
        
    }//GEN-LAST:event_ratingSpinnerStateChanged

    private void confirmarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarBotonActionPerformed
        // TODO add your handling code here:
        Opinion opinion = new Opinion((int) ratingSpinner.getValue(), opinionArea.getText(), LocalDate.now());
        ArrayList opiniones = prod.getOpiniones();
        int i = 0;
        while(!DataManager.getProductos().get(i).equals(prod)) i++;
        
        opiniones.add(opinion);
        prod.setOpiniones(opiniones);
        ArrayList productos = DataManager.getProductos();
        productos.set(i, prod);
        DataManager.setProductos(productos);
        InterfProducto interfaz = new InterfProducto();
        interfaz.setProd(prod);
        interfaz.setInterfaz();
        prevFrame.dispose();
        interfaz.setLocationRelativeTo(null);
        interfaz.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_confirmarBotonActionPerformed

    private void canclelarButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canclelarButonActionPerformed
        // TODO add your handling code here:
        prevFrame.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_canclelarButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfOpinar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfOpinar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfOpinar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfOpinar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    private Producto prod;
    private InterfProducto prevFrame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canclelarButon;
    private javax.swing.JButton confirmarBoton;
    private javax.swing.JLabel explicacionLabel;
    private javax.swing.JTextArea opinionArea;
    private javax.swing.JScrollPane opinionScroll;
    private javax.swing.JSpinner ratingSpinner;
    // End of variables declaration//GEN-END:variables
}
