/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.JavaComp.interf;

import com.JavaComp.program.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Kar�n
 */
public class ModificarDatosEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form ModificarDatosCliente
     */
    public ModificarDatosEmpresa() {
        initComponents();
        Empresa clienteEmp = (Empresa) DataManager.getClienteActual();
        cifField.setText(clienteEmp.getCif());
        webField.setText(clienteEmp.getWeb());
        nombreField.setText(clienteEmp.getNombre());
        correoField.setText(clienteEmp.getCorreo());
        telefonoField.setText(clienteEmp.getTelefono());
        calleField.setText(clienteEmp.getDireccion().getCalle());
        numeroField.setText(clienteEmp.getDireccion().getNumero());
        cpField.setText(clienteEmp.getDireccion().getCp());
        ciudadField.setText(clienteEmp.getDireccion().getCiudad());
        titularField.setText(clienteEmp.getTarjeta().getTitular());
        codigoField.setText(clienteEmp.getTarjeta().getCodigo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        cif = new javax.swing.JLabel();
        cifField = new javax.swing.JFormattedTextField();
        web = new javax.swing.JLabel();
        webField = new javax.swing.JTextField();
        nombre = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        correo = new javax.swing.JLabel();
        correoField = new javax.swing.JTextField();
        telefono = new javax.swing.JLabel();
        telefonoField = new javax.swing.JFormattedTextField();
        DIRECCION = new javax.swing.JLabel();
        calle = new javax.swing.JLabel();
        calleField = new javax.swing.JTextField();
        numero = new javax.swing.JLabel();
        numeroField = new javax.swing.JFormattedTextField();
        cp = new javax.swing.JLabel();
        cpField = new javax.swing.JFormattedTextField();
        ciudad = new javax.swing.JLabel();
        ciudadField = new javax.swing.JTextField();
        TARJETA = new javax.swing.JLabel();
        titular = new javax.swing.JLabel();
        titularField = new javax.swing.JTextField();
        codigo = new javax.swing.JLabel();
        codigoField = new javax.swing.JFormattedTextField();
        caducidad = new javax.swing.JLabel();
        caducidadDate = new org.jdatepicker.JDatePicker();
        claveActual = new javax.swing.JLabel();
        claveActualField = new javax.swing.JTextField();
        claveNueva = new javax.swing.JLabel();
        claveNuevaField = new javax.swing.JTextField();
        confirmarBoton = new javax.swing.JButton();
        cancelarBoton = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cif.setText("CIF:");

        try {
            cifField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        web.setText("Web:");

        nombre.setText("Nombre:");

        correo.setText("Correo electrónico:");

        telefono.setText("Teléfono:");

        try {
            telefonoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        DIRECCION.setText("Dirección");

        calle.setText("Calle:");

        numero.setText("Número:");

        numeroField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        cp.setText("Código postal:");

        try {
            cpField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        ciudad.setText("Ciudad:");

        TARJETA.setText("Tarjeta:");

        titular.setText("Titular:");

        codigo.setText("Codigo:");

        try {
            codigoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### #### #### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        caducidad.setText("Fecha de caducidad:");

        claveActual.setText("Contraseña actual:");

        claveNueva.setText("Nueva contraseña:");

        confirmarBoton.setText("Confirmar y modificar");
        confirmarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarBotonActionPerformed(evt);
            }
        });

        cancelarBoton.setText("Cancelar");
        cancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numero)
                                    .addComponent(calle)
                                    .addComponent(cp)
                                    .addComponent(ciudad)))
                            .addComponent(claveNueva)
                            .addComponent(DIRECCION)
                            .addComponent(claveActual))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelarBoton)
                                .addGap(3, 3, 3)
                                .addComponent(confirmarBoton))
                            .addComponent(calleField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ciudadField)
                            .addComponent(claveActualField)
                            .addComponent(claveNuevaField)
                            .addComponent(numeroField)
                            .addComponent(cpField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titular)
                            .addComponent(codigo)
                            .addComponent(caducidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(caducidadDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(titularField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(codigoField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cif)
                                    .addComponent(nombre)
                                    .addComponent(correo, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TARJETA)
                                    .addComponent(web))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(correoField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cifField, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(telefonoField)
                            .addComponent(webField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cif)
                    .addComponent(cifField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(web)
                    .addComponent(webField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correo)
                    .addComponent(correoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefono)
                    .addComponent(telefonoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DIRECCION)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calle)
                    .addComponent(calleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numero)
                        .addGap(12, 12, 12)
                        .addComponent(cp))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numeroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ciudad)
                    .addComponent(ciudadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TARJETA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titular)
                    .addComponent(titularField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo)
                    .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caducidadDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caducidad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(claveActual)
                    .addComponent(claveActualField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(claveNueva)
                    .addComponent(claveNuevaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarBoton)
                    .addComponent(cancelarBoton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotonActionPerformed
        this.setVisible(false);
        InterfCliente interfCliente = new InterfCliente();
        interfCliente.setLocation(this.getLocation());
        interfCliente.setVisible(true);
    }//GEN-LAST:event_cancelarBotonActionPerformed

    private void confirmarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarBotonActionPerformed
        if (!cifField.getText().isBlank() && !webField.getText().isBlank() && !nombreField.getText().isBlank() && !correoField.getText().isBlank()
                && !telefonoField.getText().isBlank() && !calleField.getText().isBlank() && !numeroField.getText().isBlank()
                && !cpField.getText().isBlank() && !titularField.getText().isBlank() && !codigoField.getText().isBlank() &&
                !caducidadDate.getModel().toString().isBlank()){
            if (claveActualField.getText().equals(DataManager.getClienteActual().getClave()) && claveNuevaField.getText().isBlank()){
                Empresa.ModificarEmpresa(nombreField.getText(), correoField.getText(),
                    claveActual.getText(), telefonoField.getText(), cifField.getText(), webField.getText(),
                    titularField.getText(), codigoField.getText(), caducidadDate.getDateFormat(),
                    calleField.getText(), numeroField.getText(), cpField.getText(), ciudadField.getText());
                    this.setVisible(false);
                    InterfCliente interfCliente = new InterfCliente();
                    interfCliente.setLocation(this.getLocation());
                    interfCliente.setVisible(true);
            }
            else if(claveActualField.getText().equals(DataManager.getClienteActual().getClave())){
                Empresa.ModificarEmpresa(nombreField.getText(), correoField.getText(),
                    claveNueva.getText(), telefonoField.getText(), cifField.getText(), webField.getText(),
                    titularField.getText(), codigoField.getText(), caducidadDate.getDateFormat(),
                    calleField.getText(), numeroField.getText(), cpField.getText(), ciudadField.getText());
                    this.setVisible(false);
                    InterfCliente interfCliente = new InterfCliente();
                    interfCliente.setLocation(this.getLocation());
                    interfCliente.setVisible(true);
            }
            else JOptionPane.showMessageDialog(this,"La contraseña actual no coincide.");
        }
        else JOptionPane.showMessageDialog(this, "Asegurese de introducir todos los datos");
    }//GEN-LAST:event_confirmarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarDatosEmpresa().setVisible(true);
            }
        });
    }
    public javax.swing.JFrame prevFrame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DIRECCION;
    private javax.swing.JLabel TARJETA;
    private javax.swing.JLabel caducidad;
    private org.jdatepicker.JDatePicker caducidadDate;
    private javax.swing.JLabel calle;
    private javax.swing.JTextField calleField;
    private javax.swing.JButton cancelarBoton;
    private javax.swing.JLabel cif;
    private javax.swing.JFormattedTextField cifField;
    private javax.swing.JLabel ciudad;
    private javax.swing.JTextField ciudadField;
    private javax.swing.JLabel claveActual;
    private javax.swing.JTextField claveActualField;
    private javax.swing.JLabel claveNueva;
    private javax.swing.JTextField claveNuevaField;
    private javax.swing.JLabel codigo;
    private javax.swing.JFormattedTextField codigoField;
    private javax.swing.JButton confirmarBoton;
    private javax.swing.JLabel correo;
    private javax.swing.JTextField correoField;
    private javax.swing.JLabel cp;
    private javax.swing.JFormattedTextField cpField;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel numero;
    private javax.swing.JFormattedTextField numeroField;
    private javax.swing.JLabel telefono;
    private javax.swing.JFormattedTextField telefonoField;
    private javax.swing.JLabel titular;
    private javax.swing.JTextField titularField;
    private javax.swing.JLabel web;
    private javax.swing.JTextField webField;
    // End of variables declaration//GEN-END:variables
}
