/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.JavaComp.interf;

import com.JavaComp.program.DataManager;
import com.JavaComp.program.Producto;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Pablo
 * @author Karín
 */
public class ModificarProducto extends javax.swing.JFrame {

    /**
     * Creates new form CrearProducto
     * @param prod el producto que se va a modificar
     */
    public ModificarProducto(Producto prod) {
        this.prod = prod;
        initComponents();
        index = 0;
        while (index < DataManager.getProductos().size() && !DataManager.getProductos().get(index).equals(prod)) index++;
        
        tituloField.setText(prod.getTitulo());
        caracteristicasField.setText(prod.getCaracteristicas());
        precioField.setText(Double.toString(prod.getPvp()));
        int i = -1;
        switch (prod.getCategoria()){
            case "Componentes":
                i = 0;
                break;
            case "Ordenadores":
                i = 1;
                break;
            case "Móviles y telefonía":
                i = 2;
                break;
            case "TV, audio y foto":
                i = 3;
                break;
            case "Consolas y videojuegos":
                i = 4;
                break;
                
        }
        categoriaBox.setSelectedIndex(i);
        System.out.println("\n    " + Double.toString(prod.getPvp()));
        String[] stringArray = Double.toString(prod.getPvp()).split("\\.");
        System.out.println(Arrays.toString(stringArray));
        
        String setText = stringArray[0] + "," + stringArray[1];
        System.out.println(setText);
        precioField.setText(setText);
        stockSpinner.setValue((Object) prod.getStock());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        titulo = new javax.swing.JLabel();
        tituloField = new javax.swing.JTextField();
        caracteristicas = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        categoriaBox = new javax.swing.JComboBox<>();
        pvp = new javax.swing.JLabel();
        stock = new javax.swing.JLabel();
        stockSpinner = new javax.swing.JSpinner();
        imagen = new javax.swing.JLabel();
        path = new javax.swing.JLabel();
        fileChooser = new javax.swing.JButton();
        volverBoton = new javax.swing.JButton();
        confirmarBoton = new javax.swing.JButton();
        precioField = new javax.swing.JFormattedTextField();
        caracteristicasScroll = new javax.swing.JScrollPane();
        caracteristicasField = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JavaComp");
        setIconImage(new javax.swing.ImageIcon("src/main/resources/images/LogoJavaComp.png").getImage());
        setResizable(false);

        titulo.setText("Título del producto:");

        caracteristicas.setText("Características:");

        categoria.setText("Categoría:");

        categoriaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Componentes", "Ordenadores", "Móviles y telefonía", "TV, audio y foto", "Consolas y videojuegos" }));
        categoriaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaBoxActionPerformed(evt);
            }
        });

        pvp.setText("Precio de venta:");

        stock.setText("Stock:");

        stockSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        imagen.setText("Imagen:");

        path.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        path.setText("<Seleccione imagen para modificar>");
        path.setInheritsPopupMenu(false);
        path.setMaximumSize(new java.awt.Dimension(233, 16));

        fileChooser.setText("...");
        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });

        volverBoton.setText("Volver");
        volverBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBotonActionPerformed(evt);
            }
        });

        confirmarBoton.setText("Modificar Producto");
        confirmarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarBotonActionPerformed(evt);
            }
        });

        precioField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        precioField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        precioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioFieldActionPerformed(evt);
            }
        });

        caracteristicasField.setColumns(20);
        caracteristicasField.setLineWrap(true);
        caracteristicasField.setRows(5);
        caracteristicasField.setWrapStyleWord(true);
        caracteristicasScroll.setViewportView(caracteristicasField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(caracteristicas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categoria, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pvp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(volverBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmarBoton))
                            .addComponent(tituloField)
                            .addComponent(categoriaBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stockSpinner)
                            .addComponent(precioField)
                            .addComponent(caracteristicasScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo)
                    .addComponent(tituloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caracteristicas)
                    .addComponent(caracteristicasScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoriaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pvp)
                    .addComponent(precioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stock)
                    .addComponent(stockSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagen)
                    .addComponent(path, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fileChooser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarBoton)
                    .addComponent(volverBoton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoriaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaBoxActionPerformed

    private void confirmarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarBotonActionPerformed
        if (!tituloField.getText().isBlank() && !caracteristicasField.getText().isBlank()
                && !precioField.getText().isEmpty()){
            if (!path.getText().equals("<Seleccione imagen para modificar>")){
                BufferedImage image = null;
                try {image = ImageIO.read(new File(path.getText()));}
                catch (IOException e) {System.out.print("Error de I/O: " + e.getMessage());}
                File outputImage = new File("src/main/resources/saves/savedIcons/" + tituloField.getText() +".jpg");
                try {ImageIO.write(image,"jpg", outputImage);}
                catch (IOException e) {System.out.print("Error de I/O: " + e.getMessage());}
                prod.setImagen("src/main/resources/saves/savedIcons/" + tituloField.getText() +".jpg");
            }
            
            prod.setCaracteristicas(caracteristicasField.getText());
            try{
                prod.setPvp(Double.parseDouble(precioField.getValue().toString()));
            }
            catch (Exception e){
                prod.setPvp(prod.getPvp());
            }
            prod.setCategoria(categoriaBox.getSelectedItem().toString());
            prod.setTitulo(tituloField.getText());
            
            if((int) stockSpinner.getValue() != 0) prod.setStock((int) stockSpinner.getValue());
            else JOptionPane.showMessageDialog(this, "El stock del producto no puede ser 0", "Error", JOptionPane.WARNING_MESSAGE);
            
            ArrayList<Producto> productos = DataManager.getProductos();
            productos.set(index, prod);
            DataManager.setProductos(productos);
            Inventario inventario = new Inventario();
            inventario.setLocationRelativeTo(null);
            inventario.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
        else JOptionPane.showMessageDialog(this, "Introduzca todos los datos", "Error", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_confirmarBotonActionPerformed
    
    //activa el file filter para seleccionar una imagen
    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserActionPerformed
        JFileChooser elegirImagen = new JFileChooser();
        elegirImagen.setAcceptAllFileFilterUsed(false);
        FileFilter filter = new FileNameExtensionFilter("(JPG o PNG)", "jpg");
        elegirImagen.setFileFilter(filter);
        elegirImagen.showDialog(imagen, "Elegir Imagen");
        if(elegirImagen.getSelectedFile() != null)
            path.setText(elegirImagen.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_fileChooserActionPerformed

    private void volverBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBotonActionPerformed
        this.setVisible(false);
        Inventario interf = new Inventario();
        interf.setLocationRelativeTo(null);
        interf.setVisible(true);
        dispose();
    }//GEN-LAST:event_volverBotonActionPerformed

    private void precioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    private int index;
    private Producto prod;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel caracteristicas;
    private javax.swing.JTextArea caracteristicasField;
    private javax.swing.JScrollPane caracteristicasScroll;
    private javax.swing.JLabel categoria;
    private javax.swing.JComboBox<String> categoriaBox;
    private javax.swing.JButton confirmarBoton;
    private javax.swing.JButton fileChooser;
    private javax.swing.JLabel imagen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel path;
    private javax.swing.JFormattedTextField precioField;
    private javax.swing.JLabel pvp;
    private javax.swing.JLabel stock;
    private javax.swing.JSpinner stockSpinner;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField tituloField;
    private javax.swing.JButton volverBoton;
    // End of variables declaration//GEN-END:variables
}
