/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.JavaComp.interf;

import com.JavaComp.program.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Kar�n
 */
public class ModificarDatosParticular extends javax.swing.JFrame {

    /**
     * Creates new form ModificarDatosCliente
     */
    public ModificarDatosParticular() {
        initComponents();
        Particular clientePart = (Particular) DataManager.getClienteActual();
        dniField.setText(clientePart.getDni());
        nombreField.setText(clientePart.getNombre());
        correoField.setText(clientePart.getCorreo());
        telefonoField.setText(clientePart.getTelefono());
        calleField.setText(clientePart.getDireccion().getCalle());
        numeroField.setText(clientePart.getDireccion().getNumero());
        cpField.setText(clientePart.getDireccion().getCp());
        ciudadField.setText(clientePart.getDireccion().getCiudad());
        titularField.setText(clientePart.getTarjeta().getTitular());
        codigoField.setText(clientePart.getTarjeta().getCodigo());
        fCaducidadField.setText(clientePart.getTarjeta().getCaducidad());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        dni = new javax.swing.JLabel();
        dniField = new javax.swing.JFormattedTextField();
        nombre = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        correo = new javax.swing.JLabel();
        correoField = new javax.swing.JTextField();
        telefono = new javax.swing.JLabel();
        telefonoField = new javax.swing.JFormattedTextField();
        DIRECCION = new javax.swing.JLabel();
        calle = new javax.swing.JLabel();
        calleField = new javax.swing.JTextField();
        numero = new javax.swing.JLabel();
        numeroField = new javax.swing.JFormattedTextField();
        cp = new javax.swing.JLabel();
        cpField = new javax.swing.JFormattedTextField();
        ciudad = new javax.swing.JLabel();
        ciudadField = new javax.swing.JTextField();
        TARJETA = new javax.swing.JLabel();
        titular = new javax.swing.JLabel();
        titularField = new javax.swing.JTextField();
        codigo = new javax.swing.JLabel();
        codigoField = new javax.swing.JFormattedTextField();
        caducidad = new javax.swing.JLabel();
        claveActual = new javax.swing.JLabel();
        claveNueva = new javax.swing.JLabel();
        confirmarBoton = new javax.swing.JButton();
        cancelarBoton = new javax.swing.JButton();
        claveActualField = new javax.swing.JPasswordField();
        claveNuevaField = new javax.swing.JPasswordField();
        fCaducidadField = new javax.swing.JFormattedTextField();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaComp");
        setIconImage(new javax.swing.ImageIcon("src/main/resources/images/LogoJavaComp.png").getImage());
        setResizable(false);

        dni.setText("DNI:");

        try {
            dniField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        nombre.setText("Nombre:");

        correo.setText("Correo electrónico:");

        telefono.setText("Teléfono:");

        try {
            telefonoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        DIRECCION.setText("Dirección");

        calle.setText("Calle:");

        numero.setText("Número:");

        numeroField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        cp.setText("Código postal:");

        try {
            cpField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        ciudad.setText("Ciudad:");

        TARJETA.setText("Tarjeta:");

        titular.setText("Titular:");

        codigo.setText("Codigo:");

        try {
            codigoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### #### #### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        caducidad.setText("Fecha de caducidad:");

        claveActual.setText("Contraseña actual:");

        claveNueva.setText("Nueva contraseña:");

        confirmarBoton.setBackground(new java.awt.Color(255, 191, 29));
        confirmarBoton.setForeground(new java.awt.Color(51, 51, 51));
        confirmarBoton.setText("Confirmar");
        confirmarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarBotonActionPerformed(evt);
            }
        });

        cancelarBoton.setBackground(new java.awt.Color(255, 191, 29));
        cancelarBoton.setForeground(new java.awt.Color(51, 51, 51));
        cancelarBoton.setText("Cancelar");
        cancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotonActionPerformed(evt);
            }
        });

        try {
            fCaducidadField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dni)
                            .addComponent(nombre)
                            .addComponent(correo, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(correoField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dniField, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(telefonoField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numero)
                                    .addComponent(calle)
                                    .addComponent(cp)
                                    .addComponent(ciudad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cancelarBoton)
                                        .addGap(18, 18, 18)
                                        .addComponent(confirmarBoton))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ciudadField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cpField)
                                        .addComponent(numeroField, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                        .addComponent(calleField, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titular)
                                    .addComponent(codigo)
                                    .addComponent(caducidad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(titularField)
                                    .addComponent(codigoField, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                    .addComponent(fCaducidadField, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DIRECCION)
                            .addComponent(TARJETA))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(claveActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(claveNueva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(claveActualField, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(claveNuevaField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dni)
                    .addComponent(dniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correo)
                    .addComponent(correoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefono)
                    .addComponent(telefonoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DIRECCION)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calle)
                    .addComponent(calleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero)
                    .addComponent(numeroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cp)
                    .addComponent(cpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciudad)
                    .addComponent(ciudadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TARJETA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titular)
                    .addComponent(titularField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo)
                    .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caducidad)
                    .addComponent(fCaducidadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(claveActual)
                    .addComponent(claveActualField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(claveNueva)
                    .addComponent(claveNuevaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarBoton)
                    .addComponent(confirmarBoton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotonActionPerformed
        this.setVisible(false);
        InterfCliente interfCliente = new InterfCliente();
        interfCliente.setLocationRelativeTo(null);
        interfCliente.setVisible(true);
    }//GEN-LAST:event_cancelarBotonActionPerformed

    private void confirmarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarBotonActionPerformed
             
        boolean rellenoCaducidad = true;
        boolean arr[] = new boolean[2];
        try{
            arr = TarjetaCredito.comprobarFechaTarjeta(fCaducidadField.getText());
        }
        catch (java.lang.NumberFormatException e){
            arr[0] = true;
            arr[1] = true;
            rellenoCaducidad = false;
        }
        boolean correoEsisten = false;
        for (Cliente cliente:DataManager.getClientes())
            if (cliente.getCorreo().equals(correoField.getText()) && !DataManager.getClienteActual().getCorreo().equals(correoField.getText())) correoEsisten = true;
        if (!dniField.getText().isBlank() && !nombreField.getText().isBlank() && !correoField.getText().isBlank()
                && !telefonoField.getText().isBlank() && !calleField.getText().isBlank() && !numeroField.getText().isBlank()
                && !cpField.getText().isBlank() && !titularField.getText().isBlank() && !codigoField.getText().isBlank() &&
                !fCaducidadField.getText().isBlank() && arr[0] && arr[1] && !correoEsisten && rellenoCaducidad){
            if(claveActualField.getText().equals(DataManager.getClienteActual().getClave()) && claveNuevaField.getText().isBlank()){
                Particular.ModificarParticular(nombreField.getText(), correoField.getText(),
                    claveActualField.getText(), telefonoField.getText(), dniField.getText(),
                    titularField.getText(), codigoField.getText(), fCaducidadField.getText(),
                    calleField.getText(), numeroField.getText(), cpField.getText(), ciudadField.getText());
                this.setVisible(false);
                InterfCliente interfCliente = new InterfCliente();
                interfCliente.setLocationRelativeTo(null);
                interfCliente.setVisible(true);
            }
            else if (claveActualField.getText().equals(DataManager.getClienteActual().getClave())){
                Particular.ModificarParticular(nombreField.getText(), correoField.getText(),
                    claveNuevaField.getText(), telefonoField.getText(), dniField.getText(),
                    titularField.getText(), codigoField.getText(), fCaducidadField.getText(),
                    calleField.getText(), numeroField.getText(), cpField.getText(), ciudadField.getText());
                this.setVisible(false);
                InterfCliente interfCliente = new InterfCliente();
                interfCliente.setLocationRelativeTo(null);
                interfCliente.setVisible(true);
            }
            else JOptionPane.showMessageDialog(this,"La contraseña actual no coincide.");
        }
        else if (correoEsisten) JOptionPane.showMessageDialog(this, "El correo que ha introducido ya está registrado.", "Error", JOptionPane.WARNING_MESSAGE);
        else if (!arr[1]){
            fCaducidadField.setText("");
            JOptionPane.showMessageDialog(this, "La fecha introducida no es válida, pruebe con meses entre 01 y 12");
        }
        else if (!arr[0]){
            fCaducidadField.setText("");
            JOptionPane.showMessageDialog(this, "Asegúrese de que la tarjeta que ha introducido no está caducada");
        }
        else JOptionPane.showMessageDialog(this, "Asegurese de introducir todos los datos");
    }//GEN-LAST:event_confirmarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosParticular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosParticular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosParticular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosParticular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarDatosParticular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DIRECCION;
    private javax.swing.JLabel TARJETA;
    private javax.swing.JLabel caducidad;
    private javax.swing.JLabel calle;
    private javax.swing.JTextField calleField;
    private javax.swing.JButton cancelarBoton;
    private javax.swing.JLabel ciudad;
    private javax.swing.JTextField ciudadField;
    private javax.swing.JLabel claveActual;
    private javax.swing.JPasswordField claveActualField;
    private javax.swing.JLabel claveNueva;
    private javax.swing.JPasswordField claveNuevaField;
    private javax.swing.JLabel codigo;
    private javax.swing.JFormattedTextField codigoField;
    private javax.swing.JButton confirmarBoton;
    private javax.swing.JLabel correo;
    private javax.swing.JTextField correoField;
    private javax.swing.JLabel cp;
    private javax.swing.JFormattedTextField cpField;
    private javax.swing.JLabel dni;
    private javax.swing.JFormattedTextField dniField;
    private javax.swing.JFormattedTextField fCaducidadField;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel numero;
    private javax.swing.JFormattedTextField numeroField;
    private javax.swing.JLabel telefono;
    private javax.swing.JFormattedTextField telefonoField;
    private javax.swing.JLabel titular;
    private javax.swing.JTextField titularField;
    // End of variables declaration//GEN-END:variables
}
