/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.JavaComp.interf;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import com.JavaComp.program.*;
import java.awt.Dialog;

public class SignUp extends javax.swing.JFrame {

    public SignUp() {
        initComponents();
        //Se ocultan los datos únicos de cada opción de cliente hasta que se selecciona alguno de los radio buttons
        toggleEmpresa.setVisible(false);
        toggleParticular.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buttons = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        toggle = new javax.swing.JLayeredPane();
        toggleEmpresa = new javax.swing.JPanel();
        CIF = new javax.swing.JLabel();
        cifField = new javax.swing.JTextField();
        Web = new javax.swing.JLabel();
        webField = new javax.swing.JTextField();
        toggleParticular = new javax.swing.JPanel();
        DNI = new javax.swing.JLabel();
        dniField = new javax.swing.JFormattedTextField();
        particularRadioBoton = new javax.swing.JRadioButton();
        empresaRadioBoton = new javax.swing.JRadioButton();
        Nombre = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        Correo = new javax.swing.JLabel();
        correoField = new javax.swing.JTextField();
        Clave = new javax.swing.JLabel();
        claveField = new javax.swing.JPasswordField();
        Direccion = new javax.swing.JLabel();
        direccionField = new javax.swing.JTextField();
        Telefono = new javax.swing.JLabel();
        telefonoField = new javax.swing.JFormattedTextField();
        confirmarBoton = new javax.swing.JButton();
        cancelarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaComp");
        setIconImage(new ImageIcon("images/LogoJavaComp.png").getImage());
        setResizable(false);

        toggleEmpresa.setOpaque(false);

        CIF.setText("CIF:");

        cifField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cifFieldActionPerformed(evt);
            }
        });

        Web.setText("Web:");

        javax.swing.GroupLayout toggleEmpresaLayout = new javax.swing.GroupLayout(toggleEmpresa);
        toggleEmpresa.setLayout(toggleEmpresaLayout);
        toggleEmpresaLayout.setHorizontalGroup(
            toggleEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toggleEmpresaLayout.createSequentialGroup()
                .addGroup(toggleEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CIF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Web, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addGroup(toggleEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cifField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        toggleEmpresaLayout.setVerticalGroup(
            toggleEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toggleEmpresaLayout.createSequentialGroup()
                .addGroup(toggleEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CIF)
                    .addComponent(cifField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(toggleEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Web)
                    .addComponent(webField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        DNI.setText("DNI:");

        try {
            dniField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dniField.setText("");
        dniField.setToolTipText("");
        dniField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toggleParticularLayout = new javax.swing.GroupLayout(toggleParticular);
        toggleParticular.setLayout(toggleParticularLayout);
        toggleParticularLayout.setHorizontalGroup(
            toggleParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toggleParticularLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DNI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addComponent(dniField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        toggleParticularLayout.setVerticalGroup(
            toggleParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toggleParticularLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(toggleParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DNI)
                    .addComponent(dniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        toggle.setLayer(toggleEmpresa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        toggle.setLayer(toggleParticular, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout toggleLayout = new javax.swing.GroupLayout(toggle);
        toggle.setLayout(toggleLayout);
        toggleLayout.setHorizontalGroup(
            toggleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toggleParticular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(toggleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(toggleLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(toggleEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        toggleLayout.setVerticalGroup(
            toggleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toggleLayout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addComponent(toggleParticular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(toggleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(toggleLayout.createSequentialGroup()
                    .addComponent(toggleEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 33, Short.MAX_VALUE)))
        );

        Buttons.add(particularRadioBoton);
        particularRadioBoton.setText("Particular");
        particularRadioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                particularRadioBotonActionPerformed(evt);
            }
        });

        Buttons.add(empresaRadioBoton);
        empresaRadioBoton.setText("Empresa");
        empresaRadioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaRadioBotonActionPerformed(evt);
            }
        });

        Nombre.setText("Nombre:");

        nombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFieldActionPerformed(evt);
            }
        });

        Correo.setText("Correo:");

        Clave.setText("Clave de acceso:");

        Direccion.setText("Dirección:");

        Telefono.setText("Teléfono:");

        try {
            telefonoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Direccion)
                    .addComponent(Telefono)
                    .addComponent(Clave)
                    .addComponent(Correo)
                    .addComponent(Nombre)
                    .addComponent(particularRadioBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(empresaRadioBoton))
                    .addComponent(nombreField, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(correoField)
                    .addComponent(direccionField, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(claveField, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(telefonoField))
                .addContainerGap())
            .addComponent(toggle, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empresaRadioBoton)
                    .addComponent(particularRadioBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clave, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(claveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Direccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefono)
                    .addComponent(telefonoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        confirmarBoton.setText("Confirmar y añadir la tarjeta de crédito");
        confirmarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarBotonActionPerformed(evt);
            }
        });

        cancelarBoton.setText("Cancelar");
        cancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelarBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmarBoton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarBoton)
                    .addComponent(cancelarBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empresaRadioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaRadioBotonActionPerformed
        // Se muestran los datos que hay que rellenar si el cliente es una empresa
        toggleEmpresa.setVisible(true);
        toggleParticular.setVisible(false);
    }//GEN-LAST:event_empresaRadioBotonActionPerformed

    private void nombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFieldActionPerformed

    private void particularRadioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_particularRadioBotonActionPerformed
        // Se muestran los datos que hay que rellenar si el cliente es un particular
        toggleEmpresa.setVisible(false);
        toggleParticular.setVisible(true);
    }//GEN-LAST:event_particularRadioBotonActionPerformed

    private void dniFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniFieldActionPerformed

    //confirma los datos y procede a la pestaÃ±a de introducir tarjeta
    //crea un objeto cliente para mÃ¡s tarde meterlo en la lista
    private void confirmarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarBotonActionPerformed
        /*
        if (Empresa.isSelected()){
            Empresa empresa = new Empresa(nombreField.getText(), correoField.getText(),
                    claveField.getText(), new Direccion("as","asd","asdf","asdf"), interfaz.tarjeta,
                    telefonoField.getText(), cifField.getText(), webField.getText());
            MainClass.clientes.add(empresa);
        } else{
            Particular particular = new Particular(nombreField.getText(), correoField.getText(), 
                    claveField.getText(), new Direccion("","","",""), interfaz.tarjeta,
                    telefonoField.getText(), dniField.getText());
            MainClass.clientes.add(particular);
        }
        */

        //comprueba que todo estÃ¡ relleno para pasar a el siguiente panel
        //crea un objeto cliente para aÃ±adir a la ArrayList
        if (empresaRadioBoton.isSelected()&&!cifField.getText().isEmpty()&&!webField.getText().isEmpty()
                &&!nombreField.getText().isEmpty()&&!correoField.getText().isEmpty()
                &&!claveField.getText().isEmpty()&&!direccionField.getText().isEmpty()
                &&!telefonoField.getText().isEmpty()){
            //crea un cliente de tipo empresa
            Empresa empresa = new Empresa(nombreField.getText(), correoField.getText(),
                    claveField.getText(), new Direccion("as","asd","asdf","asdf"),
                    telefonoField.getText(), cifField.getText(), webField.getText());
            interfaz.client = empresa;
            //aparece la ventana de tarjeta
            interfaz.setLocation(this.getLocation());
            interfaz.prevFrame = this;
            interfaz.setVisible(true);
            this.setVisible(false);
        }
        else if (particularRadioBoton.isSelected()&&!dniField.getText().isEmpty()&&
                !nombreField.getText().isEmpty()&&!correoField.getText().isEmpty()
                &&!claveField.getText().isEmpty()&&!direccionField.getText().isEmpty()
                &&!telefonoField.getText().isEmpty()){
            //crea un cliente de tipo particular
            Particular particular = new Particular(nombreField.getText(), correoField.getText(), 
                    claveField.getText(), new Direccion("","","",""),
                    telefonoField.getText(), dniField.getText());
            interfaz.client = particular;
            //aparece la ventana de tarjeta
            interfaz.setLocation(this.getLocation());
            interfaz.prevFrame = this;
            interfaz.setVisible(true);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(this,"Asegurese de que todos los campos estÃ¡n rellenos");
        }
    }//GEN-LAST:event_confirmarBotonActionPerformed
    
    //vuelve al menu principal
    private void cancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainMenu main = new MainMenu();
        main.setLocation(this.getLocation());
        main.setVisible(true);
    }//GEN-LAST:event_cancelarBotonActionPerformed

    private void cifFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cifFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cifFieldActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }
    
    private TarjetaInterfaz interfaz = new TarjetaInterfaz();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Buttons;
    private javax.swing.JLabel CIF;
    private javax.swing.JLabel Clave;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel DNI;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Telefono;
    private javax.swing.JLabel Web;
    private javax.swing.JButton cancelarBoton;
    private javax.swing.JTextField cifField;
    private javax.swing.JPasswordField claveField;
    private javax.swing.JButton confirmarBoton;
    private javax.swing.JTextField correoField;
    private javax.swing.JTextField direccionField;
    private javax.swing.JFormattedTextField dniField;
    private javax.swing.JRadioButton empresaRadioBoton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreField;
    private javax.swing.JRadioButton particularRadioBoton;
    private javax.swing.JFormattedTextField telefonoField;
    private javax.swing.JLayeredPane toggle;
    private javax.swing.JPanel toggleEmpresa;
    private javax.swing.JPanel toggleParticular;
    private javax.swing.JTextField webField;
    // End of variables declaration//GEN-END:variables
}
