/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.JavaComp.interf;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import com.JavaComp.program.*;
import java.util.Arrays;


public class SignUp extends javax.swing.JFrame {

    public SignUp() {
        initComponents();
        //Se ocultan los datos unicos de cada opcion de cliente hasta que se selecciona alguno de los radio buttons
        toggleEmpresa.setVisible(false);
        toggleParticular.setVisible(false);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buttons = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        toggle = new javax.swing.JLayeredPane();
        toggleEmpresa = new javax.swing.JPanel();
        CIF = new javax.swing.JLabel();
        cifField = new javax.swing.JFormattedTextField();
        Web = new javax.swing.JLabel();
        webField = new javax.swing.JTextField();
        toggleParticular = new javax.swing.JPanel();
        DNI = new javax.swing.JLabel();
        dniField = new javax.swing.JFormattedTextField();
        particularRadioBoton = new javax.swing.JRadioButton();
        empresaRadioBoton = new javax.swing.JRadioButton();
        nombre = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        correo = new javax.swing.JLabel();
        correoField = new javax.swing.JTextField();
        clave = new javax.swing.JLabel();
        claveField = new javax.swing.JPasswordField();
        telefono = new javax.swing.JLabel();
        telefonoField = new javax.swing.JFormattedTextField();
        direccionJBoton = new javax.swing.JLabel();
        calle = new javax.swing.JLabel();
        calleField = new javax.swing.JTextField();
        numero = new javax.swing.JLabel();
        cp = new javax.swing.JLabel();
        cpField = new javax.swing.JFormattedTextField();
        ciudad = new javax.swing.JLabel();
        ciudadField = new javax.swing.JTextField();
        TARJETA = new javax.swing.JLabel();
        titular = new javax.swing.JLabel();
        titularField = new javax.swing.JTextField();
        codigo = new javax.swing.JLabel();
        codigoField = new javax.swing.JFormattedTextField();
        caducidad = new javax.swing.JLabel();
        fCaducidadField = new javax.swing.JFormattedTextField();
        numeroField = new javax.swing.JFormattedTextField();
        confirmarBoton = new javax.swing.JButton();
        cancelarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaComp");
        setIconImage(new javax.swing.ImageIcon("src/main/resources/images/LogoJavaComp.png").getImage());
        setResizable(false);

        toggleEmpresa.setOpaque(false);

        CIF.setText("CIF:");

        try {
            cifField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U-########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        Web.setText("Web:");

        javax.swing.GroupLayout toggleEmpresaLayout = new javax.swing.GroupLayout(toggleEmpresa);
        toggleEmpresa.setLayout(toggleEmpresaLayout);
        toggleEmpresaLayout.setHorizontalGroup(
            toggleEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toggleEmpresaLayout.createSequentialGroup()
                .addGroup(toggleEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Web, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CIF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
                .addGroup(toggleEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cifField)
                    .addComponent(webField, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
        );
        toggleEmpresaLayout.setVerticalGroup(
            toggleEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toggleEmpresaLayout.createSequentialGroup()
                .addGroup(toggleEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CIF)
                    .addComponent(cifField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(toggleEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Web)
                    .addComponent(webField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        DNI.setText("DNI:");

        try {
            dniField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dniField.setText("");
        dniField.setToolTipText("");
        dniField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toggleParticularLayout = new javax.swing.GroupLayout(toggleParticular);
        toggleParticular.setLayout(toggleParticularLayout);
        toggleParticularLayout.setHorizontalGroup(
            toggleParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toggleParticularLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DNI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
                .addComponent(dniField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        toggleParticularLayout.setVerticalGroup(
            toggleParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toggleParticularLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(toggleParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DNI)
                    .addComponent(dniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Buttons.add(particularRadioBoton);
        particularRadioBoton.setText("Particular");
        particularRadioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                particularRadioBotonActionPerformed(evt);
            }
        });

        Buttons.add(empresaRadioBoton);
        empresaRadioBoton.setText("Empresa");
        empresaRadioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaRadioBotonActionPerformed(evt);
            }
        });

        toggle.setLayer(toggleEmpresa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        toggle.setLayer(toggleParticular, javax.swing.JLayeredPane.DEFAULT_LAYER);
        toggle.setLayer(particularRadioBoton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        toggle.setLayer(empresaRadioBoton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout toggleLayout = new javax.swing.GroupLayout(toggle);
        toggle.setLayout(toggleLayout);
        toggleLayout.setHorizontalGroup(
            toggleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toggleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(particularRadioBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                .addComponent(empresaRadioBoton)
                .addGap(37, 37, 37))
            .addComponent(toggleParticular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(toggleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(toggleLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(toggleEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        toggleLayout.setVerticalGroup(
            toggleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toggleLayout.createSequentialGroup()
                .addGroup(toggleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(particularRadioBoton)
                    .addComponent(empresaRadioBoton))
                .addGap(18, 35, Short.MAX_VALUE)
                .addComponent(toggleParticular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(toggleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toggleLayout.createSequentialGroup()
                    .addGap(0, 33, Short.MAX_VALUE)
                    .addComponent(toggleEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        nombre.setText("Nombre:");

        nombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFieldActionPerformed(evt);
            }
        });

        correo.setText("Correo:");

        clave.setText("Clave de acceso:");

        telefono.setText("Teléfono:");

        try {
            telefonoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        direccionJBoton.setText("Dirección:");

        calle.setText("Calle:");

        numero.setText("Número:");

        cp.setText("Código postal:");

        try {
            cpField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        ciudad.setText("Ciudad:");

        TARJETA.setText("Tarjeta de crédito:");

        titular.setText("Titular:");

        codigo.setText("Código:");

        try {
            codigoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### #### #### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        caducidad.setText("Fecha de caducidad:");

        try {
            fCaducidadField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fCaducidadField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fCaducidadFieldActionPerformed(evt);
            }
        });

        numeroField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toggle, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clave)
                            .addComponent(correo)
                            .addComponent(nombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreField, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(correoField)
                            .addComponent(claveField, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(telefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(telefonoField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direccionJBoton)
                            .addComponent(TARJETA))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cp)
                            .addComponent(numero)
                            .addComponent(calle)
                            .addComponent(ciudad)
                            .addComponent(titular)
                            .addComponent(codigo)
                            .addComponent(caducidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ciudadField)
                            .addComponent(cpField, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(calleField)
                            .addComponent(titularField)
                            .addComponent(codigoField)
                            .addComponent(fCaducidadField)
                            .addComponent(numeroField))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(toggle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(claveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefono)
                    .addComponent(telefonoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direccionJBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calle)
                    .addComponent(calleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero)
                    .addComponent(numeroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cp)
                    .addComponent(cpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciudad)
                    .addComponent(ciudadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TARJETA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titular)
                    .addComponent(titularField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo)
                    .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caducidad)
                    .addComponent(fCaducidadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        confirmarBoton.setBackground(new java.awt.Color(255, 191, 29));
        confirmarBoton.setForeground(new java.awt.Color(51, 51, 51));
        confirmarBoton.setText("Confirmar y crear cuenta");
        confirmarBoton.setFocusPainted(false);
        confirmarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarBotonActionPerformed(evt);
            }
        });

        cancelarBoton.setBackground(new java.awt.Color(255, 191, 29));
        cancelarBoton.setForeground(new java.awt.Color(51, 51, 51));
        cancelarBoton.setText("Cancelar");
        cancelarBoton.setFocusPainted(false);
        cancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelarBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmarBoton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarBoton)
                    .addComponent(confirmarBoton))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empresaRadioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaRadioBotonActionPerformed
        // Se muestran los datos que hay que rellenar si el cliente es una empresa
        toggleEmpresa.setVisible(true);
        toggleParticular.setVisible(false);
    }//GEN-LAST:event_empresaRadioBotonActionPerformed

    private void nombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFieldActionPerformed

    private void particularRadioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_particularRadioBotonActionPerformed
        // Se muestran los datos que hay que rellenar si el cliente es un particular
        toggleEmpresa.setVisible(false);
        toggleParticular.setVisible(true);
    }//GEN-LAST:event_particularRadioBotonActionPerformed

    private void dniFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniFieldActionPerformed

    //confirma que se han introducido datos y crea el cliente
    private void confirmarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarBotonActionPerformed
        boolean rellenoCaducidad = true;
        //comprueba que la fecha de caducidad de la tarjeta sea válida
        boolean arr[] = new boolean[2];
        try{
            arr = TarjetaCredito.comprobarFechaTarjeta(fCaducidadField.getText());
        }
        catch (java.lang.NumberFormatException e){
            arr[0] = true;
            arr[1] = true;
            rellenoCaducidad = false;
        }
        //comprueba que todo está relleno para crear el cliente
        boolean correoEsisten = false;
        for (Cliente cliente:DataManager.getClientes())
            if (cliente.getCorreo().equals(correoField.getText())) correoEsisten = true;
        if (!cifField.getText().isBlank() && !webField.getText().isBlank() || !dniField.getText().isBlank() && !correoEsisten
                && !nombreField.getText().isEmpty() && !correoField.getText().isEmpty()
                && !claveField.getText().isEmpty() && !telefonoField.getText().isEmpty() && !calleField.getText().isEmpty()
                && !numeroField.getText().isEmpty() && !cpField.getText().isEmpty()
                && !ciudadField.getText().isEmpty() && !titularField.getText().isEmpty() 
                && !codigoField.getText().isEmpty() &&!fCaducidadField.getText().isEmpty() && arr[1] && arr[0] && rellenoCaducidad)
        {
            if(particularRadioBoton.isSelected()) Particular.CrearParticular(nombreField.getText(), correoField.getText(),
                    claveField.getText(), telefonoField.getText(), dniField.getText(), titularField.getText(), codigoField.getText(), fCaducidadField.getText(),
                    calleField.getText(),numeroField.getText(),cpField.getText(),ciudadField.getText());
            else Empresa.CrearEmpresa(nombreField.getText(), correoField.getText(),
                    claveField.getText(), telefonoField.getText(), cifField.getText(), webField.getText(), titularField.getText(), codigoField.getText(), fCaducidadField.getText(),
                    calleField.getText(),numeroField.getText(),cpField.getText(),ciudadField.getText());
            InterfCliente interfCliente = new InterfCliente();
            interfCliente.setLocationRelativeTo(null);
            this.setVisible(false);
            interfCliente.setVisible(true);
        }
        else if (correoEsisten) JOptionPane.showMessageDialog(this, "El correo introducido ya existe");
        else if (!arr[1]){
            fCaducidadField.setText("");
            JOptionPane.showMessageDialog(this, "La fecha introducida no es válida, pruebe con meses entre 01 y 12");
        }
        else if (!arr[0]){
            fCaducidadField.setText("");
            JOptionPane.showMessageDialog(this, "Asegúrese de que la tarjeta que ha introducido no está caducada");
        }
        else JOptionPane.showMessageDialog(this,"Asegúrese de que todos los campos estén rellenos");
    }//GEN-LAST:event_confirmarBotonActionPerformed
    
    //vuelve al menu principal
    private void cancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotonActionPerformed
        this.setVisible(false);
        MainMenu main = new MainMenu();
        main.setLocationRelativeTo(null);
        main.setVisible(true);
    }//GEN-LAST:event_cancelarBotonActionPerformed

    private void fCaducidadFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fCaducidadFieldActionPerformed

    }//GEN-LAST:event_fCaducidadFieldActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

     
    public javax.swing.JFrame prevFrame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Buttons;
    private javax.swing.JLabel CIF;
    private javax.swing.JLabel DNI;
    private javax.swing.JLabel TARJETA;
    private javax.swing.JLabel Web;
    private javax.swing.JLabel caducidad;
    private javax.swing.JLabel calle;
    private javax.swing.JTextField calleField;
    private javax.swing.JButton cancelarBoton;
    private javax.swing.JFormattedTextField cifField;
    private javax.swing.JLabel ciudad;
    private javax.swing.JTextField ciudadField;
    private javax.swing.JLabel clave;
    private javax.swing.JPasswordField claveField;
    private javax.swing.JLabel codigo;
    private javax.swing.JFormattedTextField codigoField;
    private javax.swing.JButton confirmarBoton;
    private javax.swing.JLabel correo;
    private javax.swing.JTextField correoField;
    private javax.swing.JLabel cp;
    private javax.swing.JFormattedTextField cpField;
    private javax.swing.JLabel direccionJBoton;
    private javax.swing.JFormattedTextField dniField;
    private javax.swing.JRadioButton empresaRadioBoton;
    private javax.swing.JFormattedTextField fCaducidadField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel numero;
    private javax.swing.JFormattedTextField numeroField;
    private javax.swing.JRadioButton particularRadioBoton;
    private javax.swing.JLabel telefono;
    private javax.swing.JFormattedTextField telefonoField;
    private javax.swing.JLabel titular;
    private javax.swing.JTextField titularField;
    private javax.swing.JLayeredPane toggle;
    private javax.swing.JPanel toggleEmpresa;
    private javax.swing.JPanel toggleParticular;
    private javax.swing.JTextField webField;
    // End of variables declaration//GEN-END:variables
}
